---
title: eqozqq writes
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
brief-intro: nya~~ I'll write something here.
baseurl: ''
url: https://eqozqq.github.io
permalink: "/:year/:month/:day/:title/"
github_username: eqozqq
email: eqozqq@gmail.com
description_footer: nya~~ I'll write something here.
disqus_shortname: eqozqq
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
category_dir: category/
tag_dir: tag/
excerpt_separator: |2+




gems:
- jekyll-paginate
- jekyll-sitemap
paginate: 10
paginate_path: "/_posts/page:num/"
plugins:
- jekyll-paginate
